#!/usr/bin/env python3
"""Build a deterministic multi-view DOM/CSS raster-puppet runtime from puppet.json.

puppet.json schema v2 stores one rig per view. Parts may define expression-specific
image variants. Named poses contain per-part transform overrides.
"""
from __future__ import annotations
import argparse, json, posixpath
from pathlib import Path
from _common import read_json

TEMPLATE=r'''// Generated by Mafia AI Character Creator. Raster-puppet runtime.
const CHARACTER=__CHARACTER__;const PUPPET=__PUPPET__;const BASE_URL=new URL('.',import.meta.url);
const DEFAULT_VIEW=PUPPET.defaultView||Object.keys(PUPPET.views||{})[0];const DEFAULT_EXPRESSION=PUPPET.defaultExpression||'neutral';
function caps(){const views=Object.keys(PUPPET.views||{}),actions=[...new Set(views.flatMap(v=>Object.keys(PUPPET.views[v].poses||{})))],expressions=[DEFAULT_EXPRESSION,...new Set(views.flatMap(v=>(PUPPET.views[v].parts||[]).flatMap(p=>Object.keys(p.expressions||{}))))];return{views,actions,expressions:[...new Set(expressions)],props:[...(CHARACTER.props||[])]};}
export function getCharacterCapabilities(){return caps();}
function asset(src){return new URL(src,BASE_URL).href;}
function buildRig(def){const root=document.createElement('div');root.style.cssText=`position:absolute;inset:0;width:${def.canvas[0]}px;height:${def.canvas[1]}px;transform-origin:${def.anchor[0]}px ${def.anchor[1]}px;`;const nodes={},pending=[...(def.parts||[])];let guard=0;while(pending.length&&guard++<(def.parts||[]).length*3){const p=pending.shift();const parent=p.parent?nodes[p.parent]?.joint:root;if(p.parent&&!parent){pending.push(p);continue;}const joint=document.createElement('div');joint.dataset.part=p.id;joint.style.cssText=`position:absolute;left:${p.x}px;top:${p.y}px;width:0;height:0;transform-origin:0 0;z-index:${p.z||0};`;const img=document.createElement('img');img.alt='';img.draggable=false;img.src=asset(p.src);img.style.cssText=`position:absolute;left:${-p.pivot[0]}px;top:${-p.pivot[1]}px;max-width:none;pointer-events:none;`;joint.appendChild(img);parent.appendChild(joint);nodes[p.id]={joint,img,def:p};}if(pending.length)throw new Error('puppet hierarchy contains missing/cyclic parents');return{root,nodes,def};}
function ensure(target){if(!target)throw new Error('target required');if(target.__mafiaPuppet)return target.__mafiaPuppet;const wrap=document.createElement('div');wrap.dataset.character=CHARACTER.id;const first=PUPPET.views[DEFAULT_VIEW];wrap.style.cssText=`position:relative;width:${first.canvas[0]}px;height:${first.canvas[1]}px;transform-origin:${first.anchor[0]}px ${first.anchor[1]}px;`;target.appendChild(wrap);const rigs={};for(const [name,def] of Object.entries(PUPPET.views)){const rig=buildRig(def);rig.root.style.display='none';wrap.appendChild(rig.root);rigs[name]=rig;}const inst={root:wrap,rigs,resolved:null};target.__mafiaPuppet=inst;return inst;}
function applyRig(rig,state){const pose=rig.def.poses?.[state.action]||rig.def.poses?.idle||{};for(const [id,n] of Object.entries(rig.nodes)){const p={...(pose[id]||{}),...((state.parts||{})[id]||{})};const rot=Number(p.rotation||0),x=Number(p.x||0),y=Number(p.y||0),sx=p.scaleX==null?1:Number(p.scaleX),sy=p.scaleY==null?1:Number(p.scaleY);n.joint.style.transform=`translate(${x}px,${y}px) rotate(${rot}deg) scale(${sx},${sy})`;n.joint.style.opacity=p.opacity==null?'1':String(p.opacity);const expr=(state.expression||DEFAULT_EXPRESSION);const src=n.def.expressions?.[expr]||n.def.src;if(n.img.dataset.src!==src){n.img.src=asset(src);n.img.dataset.src=src;}}}
export function renderCharacter(target,t,state={}){const inst=ensure(target);const available=caps();const view=available.views.includes(state.view)?state.view:DEFAULT_VIEW;const expression=available.expressions.includes(state.expression)?state.expression:DEFAULT_EXPRESSION;const action=available.actions.includes(state.action)?state.action:(available.actions.includes('idle')?'idle':available.actions[0]);for(const [name,rig] of Object.entries(inst.rigs))rig.root.style.display=name===view?'block':'none';const rig=inst.rigs[view];applyRig(rig,{...state,action,expression});const scale=state.scale==null?1:Number(state.scale);inst.root.style.width=`${rig.def.canvas[0]}px`;inst.root.style.height=`${rig.def.canvas[1]}px`;inst.root.style.transformOrigin=`${rig.def.anchor[0]}px ${rig.def.anchor[1]}px`;inst.root.style.transform=`translate(${Number(state.x||0)}px,${Number(state.y||0)}px) rotate(${Number(state.rotation||0)}deg) scale(${(state.flip?-1:1)*scale},${scale})`;inst.root.style.opacity=state.opacity==null?'1':String(state.opacity);inst.resolved={action,view,expression};return inst;}
export const CHARACTER_MANIFEST=CHARACTER;export const PUPPET_MANIFEST=PUPPET;
'''

README='''# __NAME__\n\nRaster-puppet character generated with **Mafia AI Character Creator**.\n\n## Runtime requirements\n\n- Modern browser with DOM/CSS and ES modules.\n- `renderer/character.js`.\n- `assets/puppet.json` and every image under `assets/parts/` referenced by it.\n- No Python/Pillow/Playwright/image model is required to play the finished character.\n\nThe host may animate the root and individual joints through state/GSAP. Keep the package folder structure intact.\n'''

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('package');p.add_argument('--puppet',default='assets/puppet.json');p.add_argument('--output',default='renderer/character.js');p.add_argument('--sync-manifest',action='store_true',help='Align character.json views/actions/expressions to actual puppet capabilities before building');a=p.parse_args()
    root=Path(a.package).expanduser().resolve();m=read_json(root/'character.json');pp=root/a.puppet;puppet=read_json(pp)
    if puppet.get('schemaVersion')!=2 or not isinstance(puppet.get('views'),dict) or not puppet['views']:raise SystemExit('puppet.json schemaVersion 2 with non-empty views is required')
    implemented_views=set(puppet['views']);implemented_actions=set();implemented_expr={puppet.get('defaultExpression','neutral')}
    for view,rig in puppet['views'].items():
        for key in ['canvas','anchor','parts','poses']:
            if key not in rig:raise SystemExit(f'view {view} missing {key}')
        ids={x.get('id') for x in rig['parts']};
        if None in ids or len(ids)!=len(rig['parts']):raise SystemExit(f'view {view}: part ids must be present and unique')
        implemented_actions.update(rig['poses'])
        for part in rig['parts']:
            if part.get('parent') and part['parent'] not in ids:raise SystemExit(f"view {view}: missing parent {part['parent']} for {part['id']}")
            refs=[part.get('src')]+list((part.get('expressions') or {}).values());implemented_expr.update((part.get('expressions') or {}).keys())
            for rel in refs:
                f=pp.parent/rel
                if not f.is_file():raise SystemExit(f'missing puppet asset: {f}')
                # Rewrite paths relative to the renderer module.
                new=posixpath.relpath(f.as_posix(),(root/a.output).parent.as_posix())
                if rel==part.get('src'):part['src']=new
                else:
                    for k,v in list((part.get('expressions') or {}).items()):
                        if v==rel:part['expressions'][k]=new
    actions_by_view={v:set((rig.get('poses') or {}).keys()) for v,rig in puppet['views'].items()}
    if a.sync_manifest:
        ordered_views=list(puppet['views'])
        required=[v for v in (m.get('requiredViews') or m.get('views') or []) if v in implemented_views] or [puppet.get('defaultView') if puppet.get('defaultView') in implemented_views else ordered_views[0]]
        common=set(actions_by_view[required[0]])
        for v in required[1:]: common &= actions_by_view[v]
        old_actions=list(m.get('actions') or [])
        m['views']=ordered_views;m['requiredViews']=required;m['actions']=[x for x in old_actions if x in common]+sorted(common-set(old_actions));m['expressions']=sorted(implemented_expr)
    else:
        for key,impl in [('views',implemented_views),('actions',implemented_actions),('expressions',implemented_expr)]:
            missing=set(m.get(key) or [])-impl
            if missing:raise SystemExit(f'puppet does not implement declared {key}: {sorted(missing)}. Use --sync-manifest to align character.json.')
        # Every declared action must exist in every required view to avoid silent pose fallback.
        for view in m.get('requiredViews') or []:
            if view not in puppet['views']:raise SystemExit(f'puppet missing required view: {view}. Use --sync-manifest to align character.json.')
            miss=set(m.get('actions') or [])-set(puppet['views'][view]['poses'])
            if miss:raise SystemExit(f'view {view} missing declared poses: {sorted(miss)}')
    m['renderMode']='raster-puppet';m['entry']=a.output;m['moduleSystem']='esm';(root/'character.json').write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    src=TEMPLATE.replace('__CHARACTER__',json.dumps(m,ensure_ascii=False,indent=2)).replace('__PUPPET__',json.dumps(puppet,ensure_ascii=False,indent=2));out=root/a.output;out.parent.mkdir(parents=True,exist_ok=True);out.write_text(src,encoding='utf-8')
    readme=root/'README.md'
    if not readme.exists():readme.write_text(README.replace('__NAME__',m['displayName']),encoding='utf-8')
    print(out)
if __name__=='__main__':main()
