#!/usr/bin/env python3
"""Build a deterministic ESM sprite runtime from atlas metadata.

The generated runtime resolves action + view + expression, supports loop and
one-shot clips, uses action-local time, and resolves the atlas relative to the
module with import.meta.url (not relative to the page).
"""
from __future__ import annotations
import argparse, json, posixpath
from pathlib import Path
from _common import read_json

TEMPLATE = r'''// Generated by Mafia AI Character Creator. Deterministic generated-art runtime.
const CHARACTER = __CHARACTER__;
const ATLAS = __ATLAS__;
const ATLAS_URL = new URL(CHARACTER.spriteImage, import.meta.url).href;
const DEFAULT_VIEW = CHARACTER.defaultView || ATLAS.views?.[0] || 'front';
const DEFAULT_EXPRESSION = CHARACTER.defaultExpression || ATLAS.expressions?.[0] || 'neutral';

function available() {
  return { views:[...(ATLAS.views||[])], actions:Object.keys(ATLAS.actions||{}), expressions:[...(ATLAS.expressions||[])], props:[...(CHARACTER.props||[])] };
}
export function getCharacterCapabilities(){ return available(); }

function candidates(view, expression, action) {
  return [
    `${view}|${expression}|${action}`,
    `${view}|${DEFAULT_EXPRESSION}|${action}`,
    `${DEFAULT_VIEW}|${expression}|${action}`,
    `${DEFAULT_VIEW}|${DEFAULT_EXPRESSION}|${action}`,
  ];
}
function resolveClip(state={}) {
  const action=state.action || CHARACTER.actions?.[0] || Object.keys(ATLAS.actions||{})[0];
  const view=state.view || DEFAULT_VIEW; const expression=state.expression || DEFAULT_EXPRESSION;
  for(const id of candidates(view,expression,action)) if(ATLAS.clips?.[id]) return ATLAS.clips[id];
  const ids=ATLAS.actions?.[action] || []; if(ids.length && ATLAS.clips?.[ids[0]]) return ATLAS.clips[ids[0]];
  const first=Object.values(ATLAS.clips||{})[0]; return first || null;
}
export function resolveCharacterState(state={}) {
  const clip=resolveClip(state); return clip ? {clipId:clip.id, view:clip.view, expression:clip.expression, action:clip.action, playback:clip.playback, fps:clip.fps} : null;
}
export function resolveCharacterFrame(t,state={}) {
  const clip=resolveClip(state); if(!clip) return null; const frame=frameFor(clip,t,state); return frame ? {...resolveCharacterState(state), frame:frame.index, source:frame.source} : null;
}
function localTime(t,state,clip){
  if(Number.isFinite(state.actionTime)) return Math.max(0,state.actionTime);
  if(Number.isFinite(state.actionStart)) return Math.max(0,t-state.actionStart);
  // A one-shot without an explicit local/start time must begin at frame 0, never at an arbitrary global-time phase.
  return clip.playback==='once' ? 0 : Math.max(0,t);
}
function frameFor(clip,t,state){
  const frames=clip?.frames||[]; if(!frames.length) return null;
  if(Number.isInteger(state.frame)) return frames[Math.max(0,Math.min(frames.length-1,state.frame))];
  const raw=Math.floor(localTime(t,state,clip)*(clip.fps||12)+1e-9);
  const i=clip.playback==='once' ? Math.min(frames.length-1,raw) : ((raw%frames.length)+frames.length)%frames.length;
  return frames[i];
}
function ensureInstance(target){
  if(!target) throw new Error('renderCharacter target is required');
  if(target.__mafiaAICharacterInstance) return target.__mafiaAICharacterInstance;
  const el=document.createElement('div'); el.dataset.character=CHARACTER.id;
  const w=ATLAS.cellWidth,h=ATLAS.cellHeight,[aw,ah]=ATLAS.atlasSize;
  const ax=ATLAS.anchor?.x ?? w/2, ay=ATLAS.anchor?.y ?? h;
  el.style.cssText=`width:${w}px;height:${h}px;background-image:url("${ATLAS_URL}");background-repeat:no-repeat;background-size:${aw}px ${ah}px;transform-origin:${ax}px ${ay}px;will-change:transform,background-position;`;
  target.appendChild(el); const instance={root:el,action:null,frame:-1,resolved:null}; target.__mafiaAICharacterInstance=instance; return instance;
}
export function renderCharacter(target,t,state={}){
  const inst=ensureInstance(target); const clip=resolveClip(state); if(!clip) return inst; const frame=frameFor(clip,t,state); if(!frame) return inst;
  const [x,y,w,h]=frame.cell; inst.root.style.backgroundPosition=`${-x}px ${-y}px`; inst.root.style.width=`${w}px`; inst.root.style.height=`${h}px`;
  const scale=state.scale==null?1:Number(state.scale), sx=(state.flip?-1:1)*scale*(state.scaleX==null?1:Number(state.scaleX)), sy=scale*(state.scaleY==null?1:Number(state.scaleY));
  inst.root.style.transform=`translate(${Number(state.x||0)}px, ${Number(state.y||0)}px) rotate(${Number(state.rotation||0)}deg) scale(${sx}, ${sy})`;
  inst.root.style.opacity=state.opacity==null?'1':String(state.opacity); inst.root.dataset.clip=clip.id; inst.root.dataset.action=clip.action; inst.root.dataset.view=clip.view; inst.root.dataset.expression=clip.expression;
  inst.action=clip.action; inst.frame=frame.index; inst.resolved={clipId:clip.id,action:clip.action,view:clip.view,expression:clip.expression,playback:clip.playback,frame:frame.index}; return inst;
}
export const CHARACTER_MANIFEST=CHARACTER;
'''

DEMO=r'''<!doctype html><meta charset="utf-8"><title>__NAME__ demo</title>
<style>html,body{margin:0;background:#f4f4f4;font-family:system-ui}#qa-stage{width:512px;height:512px;margin:32px auto;background:#fff;display:grid;place-items:center;overflow:hidden}</style>
<div id="qa-stage"></div>
<script type="module">
import {renderCharacter,getCharacterCapabilities} from './__ENTRY__';
const stage=document.querySelector('#qa-stage');
window.__characterQA={
  capabilities:getCharacterCapabilities,
  renderAt(t,state={}){const inst=renderCharacter(stage,t,state);return {resolved:inst.resolved,capabilities:getCharacterCapabilities()};}
};
window.__characterQA.renderAt(0,{action:'__ACTION__',view:'__VIEW__',expression:'__EXPR__',actionTime:0});
</script>
'''

RUNTIME_README = r'''# __NAME__

Reusable character package generated with **Mafia AI Character Creator**.

## What this character needs at runtime

- A modern browser with JavaScript ES modules and DOM/CSS support.
- `renderer/character.js`.
- `assets/__ATLAS__` and `assets/atlas.json`; keep their relative paths intact.
- No Python, Pillow, Playwright, image-generation model, or Mafia AI skill is needed to **play** the finished character. Those are authoring/QA dependencies only.

Serve the folder over HTTP during development (for example `python -m http.server`) because browsers may restrict ES modules from `file://`.

## Basic use

```js
import { renderCharacter } from "./renderer/character.js";
renderCharacter(document.querySelector("#character"), 0, {
  action: "__ACTION__",
  view: "__VIEW__",
  expression: "__EXPR__",
  actionTime: 0
});
```

For one-shot actions, advance `actionTime` from zero. Looping actions can use global time. `view` and `expression` resolve through the atlas variants with documented fallbacks.

Open `demo.html` after serving the directory to verify the package.
'''

def main():
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('package'); p.add_argument('--atlas-metadata',default='assets/atlas.json'); p.add_argument('--output',default='renderer/character.js'); p.add_argument('--demo',default='demo.html'); p.add_argument('--sync-manifest',action='store_true'); a=p.parse_args()
    root=Path(a.package).expanduser().resolve(); manifest=read_json(root/'character.json'); atlas=read_json(root/a.atlas_metadata)
    if atlas.get('schemaVersion')!=2: raise SystemExit('atlas metadata schemaVersion 2 required; rebuild with compose_sprite_atlas.py')
    implemented={'views':set(atlas.get('views') or []),'actions':set((atlas.get('actions') or {}).keys()),'expressions':set(atlas.get('expressions') or [])}
    for key in ['views','actions','expressions']:
        declared=set(manifest.get(key) or []); missing=declared-implemented[key]
        if missing and not a.sync_manifest: raise SystemExit(f'atlas does not implement declared {key}: {sorted(missing)} (use --sync-manifest only if you intentionally want manifest claims reduced)')
        if a.sync_manifest: manifest[key]=sorted(implemented[key])
    output=Path(a.output); asset_abs=(root/a.atlas_metadata).parent/atlas['image']; rel=posixpath.relpath(asset_abs.as_posix(),(root/output).parent.as_posix())
    manifest['entry']=output.as_posix(); manifest['renderMode']='generated-art'; manifest['moduleSystem']='esm'; manifest['spriteImage']=rel
    manifest.setdefault('defaultView',(manifest.get('requiredViews') or manifest.get('views') or ['front'])[0]); manifest.setdefault('defaultExpression',(manifest.get('expressions') or ['neutral'])[0])
    (root/'character.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    src=TEMPLATE.replace('__CHARACTER__',json.dumps(manifest,ensure_ascii=False,indent=2)).replace('__ATLAS__',json.dumps(atlas,ensure_ascii=False,indent=2))
    out=root/output; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(src,encoding='utf-8')
    if a.demo:
        d=root/a.demo; entry_rel=posixpath.relpath(out.as_posix(),d.parent.as_posix()); entry_rel=entry_rel if entry_rel.startswith(('.', '/')) else './'+entry_rel; first_action=(manifest.get('actions') or ['idle'])[0]; first_view=manifest['defaultView']; first_expr=manifest['defaultExpression']
        d.write_text(DEMO.replace('__NAME__',manifest['displayName']).replace('__ENTRY__',entry_rel).replace('__ACTION__',first_action).replace('__VIEW__',first_view).replace('__EXPR__',first_expr),encoding='utf-8')
    readme=root/'README.md'
    if not readme.exists():
        readme.write_text(RUNTIME_README.replace('__NAME__',manifest['displayName']).replace('__ATLAS__',atlas['image']).replace('__ACTION__',(manifest.get('actions') or ['idle'])[0]).replace('__VIEW__',manifest['defaultView']).replace('__EXPR__',manifest['defaultExpression']),encoding='utf-8')
    print(json.dumps({'ok':True,'renderer':str(out),'demo':str(root/a.demo) if a.demo else None,'spriteImage':rel},indent=2))
if __name__=='__main__': main()
