#!/usr/bin/env python3
"""Extract irregular generated-sheet cells by connected alpha components.

Use after real alpha cleanup. This is safer than equal-grid slicing when limbs,
props, or poses cross nominal cell boundaries. Components can be merged with
--connect-radius to reconnect tiny antialiased gaps.

The default `reading` order clusters components into visual rows using vertical
centre/overlap, then sorts each row left-to-right. This is intentionally more
robust than sorting by top edge: image models often centre parts of different
heights on the same visual row.

A labelled QA contact sheet is generated by default. Review it before using the
extracted names to build a rig; semantic labels are not inferred from pixels.
"""
from __future__ import annotations
import argparse, json, math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageFont


def names(value,count):
    out=[x.strip() for x in value.split(',') if x.strip()] if value else []
    if out and len(out)!=count: raise SystemExit(f'--names expected {count} names, got {len(out)}')
    return out or [f'component-{i:02d}' for i in range(count)]


def components(mask:Image.Image,min_area:int):
    work=mask.copy(); found=[]
    while True:
        box=work.getbbox()
        if not box: break
        l,t,r,b=box; crop=work.crop(box); raw=crop.tobytes(); pos=next((i for i,v in enumerate(raw) if v),-1)
        if pos<0: break
        cw=crop.width; seed=(l+(pos%cw),t+(pos//cw))
        ImageDraw.floodfill(work,seed,128,thresh=0)
        comp=work.point(lambda v:255 if v==128 else 0); cbox=comp.getbbox()
        if cbox:
            hist=comp.histogram(); area=hist[255]
            if area>=min_area: found.append((cbox,area))
        work=work.point(lambda v:0 if v==128 else v)
    return found


def vertical_overlap(a,b):
    at,ab=a[1],a[3]; bt,bb=b[1],b[3]
    return max(0,min(ab,bb)-max(at,bt))


def reading_order(comps):
    """Group by visual row using centres and interval overlap, then x order."""
    if not comps:return []
    items=[]
    for box,area in comps:
        l,t,r,b=box; items.append({'box':box,'area':area,'cx':(l+r)/2,'cy':(t+b)/2,'h':b-t})
    items.sort(key=lambda z:(z['cy'],z['cx']))
    rows=[]
    for item in items:
        best=None;best_score=None
        for row in rows:
            # Compare with the row's robust centre and representative vertical band.
            row_cy=sum(x['cy'] for x in row)/len(row)
            row_h=sorted(x['h'] for x in row)[len(row)//2]
            row_box=(0,min(x['box'][1] for x in row),0,max(x['box'][3] for x in row))
            ov=vertical_overlap(item['box'],row_box)
            min_h=max(1,min(item['h'],row_h))
            centre_distance=abs(item['cy']-row_cy)
            # A component belongs to the row when its centre is close to the row
            # centre OR it substantially overlaps the row vertically.
            compatible=centre_distance<=0.55*max(item['h'],row_h) or ov/min_h>=0.35
            if compatible:
                score=centre_distance-(ov/min_h)*max(item['h'],row_h)*0.2
                if best_score is None or score<best_score:best,best_score=row,score
        if best is None:rows.append([item])
        else:best.append(item)
    rows.sort(key=lambda row:sum(x['cy'] for x in row)/len(row))
    ordered=[]
    for row in rows:
        row.sort(key=lambda x:x['cx'])
        ordered.extend((x['box'],x['area']) for x in row)
    return ordered


def make_qa_sheet(records,out_path:Path,tile=260,cols=4):
    if not records:return
    cols=max(1,min(cols,len(records))); rows=math.ceil(len(records)/cols);label_h=34
    sheet=Image.new('RGB',(cols*tile,rows*(tile+label_h)),'white');draw=ImageDraw.Draw(sheet);font=ImageFont.load_default()
    for i,rec in enumerate(records):
        with Image.open(rec['path']) as opened: crop=opened.convert('RGBA')
        scale=min((tile-24)/max(1,crop.width),(tile-24)/max(1,crop.height),1.0)
        size=(max(1,round(crop.width*scale)),max(1,round(crop.height*scale)))
        if size!=crop.size:crop=crop.resize(size,Image.Resampling.LANCZOS)
        bg=Image.new('RGBA',(tile,tile),(245,245,245,255));x=(tile-crop.width)//2;y=(tile-crop.height)//2;bg.alpha_composite(crop,(x,y))
        ox=(i%cols)*tile;oy=(i//cols)*(tile+label_h);sheet.paste(bg.convert('RGB'),(ox,oy));draw.rectangle((ox,oy,ox+tile-1,oy+tile-1),outline=(205,205,205),width=1)
        label=f"{i:02d}  {rec['name']}";draw.text((ox+8,oy+tile+9),label,fill='black',font=font)
    out_path.parent.mkdir(parents=True,exist_ok=True);sheet.save(out_path)


def main():
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('input'); p.add_argument('--output-dir',required=True); p.add_argument('--names',default='')
    p.add_argument('--alpha-threshold',type=int,default=16); p.add_argument('--min-area',type=int,default=150); p.add_argument('--padding',type=int,default=8); p.add_argument('--connect-radius',type=int,default=1); p.add_argument('--sort',choices=['reading','x','y','area'],default='reading'); p.add_argument('--json-out',default='')
    p.add_argument('--qa-sheet',default='',help='Labelled contact sheet path. Default: <output-dir>/_components-qa.png')
    p.add_argument('--no-qa-sheet',action='store_true',help='Disable the labelled QA contact sheet (not recommended for named rig parts).')
    a=p.parse_args()
    src=Path(a.input).expanduser().resolve(); out=Path(a.output_dir).expanduser().resolve(); out.mkdir(parents=True,exist_ok=True)
    with Image.open(src) as opened: im=opened.convert('RGBA')
    mask=im.getchannel('A').point(lambda v:255 if v>a.alpha_threshold else 0)
    if a.connect_radius>0:
        size=a.connect_radius*2+1; mask=mask.filter(ImageFilter.MaxFilter(size))
    comps=components(mask,a.min_area)
    if a.sort=='reading': comps=reading_order(comps)
    elif a.sort=='x': comps.sort(key=lambda x:((x[0][0]+x[0][2])/2,(x[0][1]+x[0][3])/2))
    elif a.sort=='y': comps.sort(key=lambda x:((x[0][1]+x[0][3])/2,(x[0][0]+x[0][2])/2))
    else: comps.sort(key=lambda x:-x[1])
    nms=names(a.names,len(comps)); records=[]
    for i,((l,t,r,b),area) in enumerate(comps):
        l=max(0,l-a.padding);t=max(0,t-a.padding);r=min(im.width,r+a.padding);b=min(im.height,b+a.padding)
        crop=im.crop((l,t,r,b)); path=out/f'{nms[i]}.png'; crop.save(path); records.append({'name':nms[i],'path':str(path),'box':[l,t,r,b],'center':[round((l+r)/2,2),round((t+b)/2,2)],'area':area})
    qa=None
    if not a.no_qa_sheet:
        qa=Path(a.qa_sheet).expanduser().resolve() if a.qa_sheet else out/'_components-qa.png';make_qa_sheet(records,qa)
    report={'ok':True,'input':str(src),'count':len(records),'sort':a.sort,'components':records,'qaSheet':str(qa) if qa else None,'reviewRequired':bool(a.names and qa)}
    if a.json_out:
        q=Path(a.json_out).expanduser().resolve();q.parent.mkdir(parents=True,exist_ok=True);q.write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(report,indent=2))
if __name__=='__main__': main()
