#!/usr/bin/env python3
"""Export a character package into a configured HyperFrames kit target.

Supported authoring routes:
- generated-art / raster-sprites: sprite atlas -> target runtime namespace
- raster-puppet: articulated image parts -> target runtime namespace

The exported runtime is non-ESM so the target kit builder can embed it. It uses
the configured runtime's `porCuadro` helper for seek-safe playback and optional
`anim` helpers for wrapper acting.

By default this command only writes the target's configured character directory.
With --finalize, it applies the target's version policy and runs configured
build/catalog commands. Finalization is opt-in because those are repository mutations.
"""
from __future__ import annotations
import argparse, json, re, shutil, subprocess, tempfile
from pathlib import Path
from PIL import Image
from _common import read_json, slugify, write_json


def namespace_for(slug: str) -> str:
    parts = [p for p in re.split(r'[^A-Za-z0-9]+', slug) if p]
    return (parts[0].lower() + ''.join(x[:1].upper() + x[1:] for x in parts[1:])) if parts else 'character'


def js_json(value) -> str:
    # Keep the generated kit JS safe for HTML script embedding.
    return json.dumps(value, ensure_ascii=False, separators=(',', ':')).replace('<', r'\u003c')


SPRITE_JS = r'''/* Generated by Mafia AI Character Creator for HyperFrames. */
(function(){
  "use strict";
  const M=window.__RUNTIME__;if(!M)throw new Error("__NS__ requires window.__RUNTIME__");
  const CHARACTER=__CHARACTER__;const ATLAS=__ATLAS__;
  const DEFAULT_VIEW=CHARACTER.defaultView||ATLAS.views?.[0]||"front";const DEFAULT_EXPRESSION=CHARACTER.defaultExpression||ATLAS.expressions?.[0]||"neutral";
  const ids=(v,e,a)=>[`${v}|${e}|${a}`,`${v}|${DEFAULT_EXPRESSION}|${a}`,`${DEFAULT_VIEW}|${e}|${a}`,`${DEFAULT_VIEW}|${DEFAULT_EXPRESSION}|${a}`];
  function clipFor(state={}){const a=state.action||CHARACTER.actions?.[0]||Object.keys(ATLAS.actions||{})[0],v=state.view||DEFAULT_VIEW,e=state.expression||DEFAULT_EXPRESSION;for(const id of ids(v,e,a))if(ATLAS.clips?.[id])return ATLAS.clips[id];const list=ATLAS.actions?.[a]||[];return ATLAS.clips?.[list[0]]||Object.values(ATLAS.clips||{})[0]||null;}
  function frameFor(clip,t,state={}){const f=clip?.frames||[];if(!f.length)return null;const local=Number.isFinite(state.actionTime)?Math.max(0,state.actionTime):Number.isFinite(state.actionStart)?Math.max(0,t-state.actionStart):(clip.playback==="once"?0:Math.max(0,t));const raw=Math.floor(local*(clip.fps||12)+1e-9);const i=clip.playback==="once"?Math.min(f.length-1,raw):((raw%f.length)+f.length)%f.length;return f[i];}
  function draw(c,t,state={}){const clip=clipFor(state),frame=frameFor(clip,t,state);if(!clip||!frame)return c;const [x,y,w,h]=frame.cell;c.sprite.style.backgroundPosition=`${-x}px ${-y}px`;c.sprite.dataset.action=clip.action;c.sprite.dataset.view=clip.view;c.sprite.dataset.expression=clip.expression;c.resolved={action:clip.action,view:clip.view,expression:clip.expression,playback:clip.playback,frame:frame.index,clipId:clip.id};return c;}
  M.__NS__={
    manifest:CHARACTER,atlas:ATLAS,
    capacidades(){return{views:[...(ATLAS.views||[])],actions:Object.keys(ATLAS.actions||{}),expressions:[...(ATLAS.expressions||[])],props:[...(CHARACTER.props||[])]};},
    insertar(padre,prefijo="__SLUG__",opts={}){padre=M.$(padre);const wrap=M.html("div",{id:prefijo+"-wrap",class:"__SLUG__-wrap"},padre);const stage=M.html("div",{id:prefijo+"-stage",class:"__SLUG__-stage"},wrap);const sprite=M.html("div",{id:prefijo+"-sprite",class:"__SLUG__-sprite"},stage);const w=ATLAS.cellWidth,h=ATLAS.cellHeight,[aw,ah]=ATLAS.atlasSize,ax=ATLAS.anchor?.x??w/2,ay=ATLAS.anchor?.y??h;const ancho=Number(opts.ancho||w),baseScale=ancho/w,alto=h*baseScale;const src=opts.src||"__ASSET_PREFIX__/__SLUG__/atlas.webp";wrap.style.cssText=`position:absolute;width:${ancho}px;height:${alto}px;transform-origin:${ax*baseScale}px ${ay*baseScale}px;${opts.estilo||""}`;stage.style.cssText=`position:absolute;left:0;top:0;width:${w}px;height:${h}px;transform:scale(${baseScale});transform-origin:0 0;`;sprite.style.cssText=`width:${w}px;height:${h}px;background-image:url("${src}");background-repeat:no-repeat;background-size:${aw}px ${ah}px;`;const c={wrap,stage,sprite,resolved:null,src,ancho,baseScale};draw(c,0,{action:opts.action||CHARACTER.actions?.[0],view:opts.view||DEFAULT_VIEW,expression:opts.expression||DEFAULT_EXPRESSION,actionTime:0});return c;},
    pintar:draw,
    animar(tl,c,at,dur,state={}){M.porCuadro(tl,at,dur,p=>draw(c,p*dur,{...state,actionTime:p*dur}),"none");return c;},
    accion(tl,c,action,at,dur,opts={}){return this.animar(tl,c,at,dur,{...opts,action});},
    entrar(tl,c,at=0,desde="abajo",dur=.65){const d={abajo:{y:300},izquierda:{x:-400},derecha:{x:400}}[desde]||{y:300};tl.fromTo(c.wrap,{...d,opacity:0},{x:0,y:0,opacity:1,duration:dur,ease:"back.out(1.4)"},at);return c;},
    saltar(tl,c,at=0,dur=.8,altura=70){if(!M.anim)return tl.fromTo(c.wrap,{y:0},{y:-altura,duration:dur/2,yoyo:true,repeat:1,ease:"power2.out"},at),c;M.porCuadro(tl,at,dur,p=>{const t=p*dur,j=M.anim.jump(t,dur*.18,dur*.78,altura);gsap.set(c.wrap,{y:j.y,scaleX:1+j.squash*.45,scaleY:1-j.squash,transformOrigin:"50% 100%"});},"none");return c;},
    reaccionar(tl,c,at=0,dur=.55,intensidad=1){if(!M.anim)return c;M.porCuadro(tl,at,dur,p=>{const q=M.anim.take(p*dur,.08,intensidad);gsap.set(c.wrap,{y:q.y*18,scaleX:1+q.squash*.35,scaleY:1-q.squash,transformOrigin:"50% 100%"});},"none");return c;}
  };
})();
'''

PUPPET_JS = r'''/* Generated by Mafia AI Character Creator for HyperFrames. Raster puppet. */
(function(){
  "use strict";
  const M=window.__RUNTIME__;if(!M)throw new Error("__NS__ requires window.__RUNTIME__");
  const CHARACTER=__CHARACTER__,PUPPET=__PUPPET__;const DEFAULT_VIEW=PUPPET.defaultView||Object.keys(PUPPET.views||{})[0],DEFAULT_EXPRESSION=PUPPET.defaultExpression||"neutral";
  const num=(v,d)=>Number.isFinite(Number(v))?Number(v):d;const mix=(a,b,p)=>a+(b-a)*p;
  function capabilities(){const views=Object.keys(PUPPET.views||{}),actions=[...new Set(views.flatMap(v=>Object.keys(PUPPET.views[v].poses||{})))],expressions=[DEFAULT_EXPRESSION,...new Set(views.flatMap(v=>(PUPPET.views[v].parts||[]).flatMap(p=>Object.keys(p.expressions||{}))))];return{views,actions,expressions:[...new Set(expressions)],props:[...(CHARACTER.props||[])]};}
  function buildRig(parent,name,def,base){const root=M.html("div",{class:"__SLUG__-view",'data-view':name},parent);root.style.cssText=`position:absolute;left:0;top:0;width:${def.canvas[0]}px;height:${def.canvas[1]}px;display:none;`;const nodes={},pending=[...(def.parts||[])];let guard=0;while(pending.length&&guard++<(def.parts||[]).length*4){const p=pending.shift(),host=p.parent?nodes[p.parent]?.joint:root;if(p.parent&&!host){pending.push(p);continue;}const joint=M.html("div",{class:"__SLUG__-joint",'data-part':p.id},host);joint.style.cssText=`position:absolute;left:${p.x}px;top:${p.y}px;width:0;height:0;transform-origin:0 0;z-index:${p.z||0};`;const img=M.html("img",{alt:"",draggable:"false"},joint);img.src=base+p.src;img.style.cssText=`position:absolute;left:${-p.pivot[0]}px;top:${-p.pivot[1]}px;max-width:none;pointer-events:none;`;nodes[p.id]={joint,img,def:p};}if(pending.length)throw new Error("puppet hierarchy has missing/cyclic parents");return{root,nodes,def};}
  function poseValue(pose,id,key,def){const x=pose?.[id]?.[key];return x==null?def:num(x,def);}
  function apply(c,state={},progress=1){const caps=capabilities(),view=caps.views.includes(state.view)?state.view:DEFAULT_VIEW,expr=caps.expressions.includes(state.expression)?state.expression:DEFAULT_EXPRESSION,action=caps.actions.includes(state.action)?state.action:(caps.actions.includes("idle")?"idle":caps.actions[0]),rig=c.rigs[view],fromAction=state.fromAction||"idle",from=rig.def.poses?.[fromAction]||{},to=rig.def.poses?.[action]||{};for(const [name,r] of Object.entries(c.rigs))r.root.style.display=name===view?"block":"none";for(const [id,n] of Object.entries(rig.nodes)){const extra=(state.parts||{})[id]||{},a={rotation:poseValue(from,id,"rotation",0),x:poseValue(from,id,"x",0),y:poseValue(from,id,"y",0),scaleX:poseValue(from,id,"scaleX",1),scaleY:poseValue(from,id,"scaleY",1),opacity:poseValue(from,id,"opacity",1)},b={rotation:poseValue(to,id,"rotation",0),x:poseValue(to,id,"x",0),y:poseValue(to,id,"y",0),scaleX:poseValue(to,id,"scaleX",1),scaleY:poseValue(to,id,"scaleY",1),opacity:poseValue(to,id,"opacity",1)};for(const k of Object.keys(extra))if(k in b)b[k]=num(extra[k],b[k]);const p=Math.max(0,Math.min(1,progress));n.joint.style.transform=`translate(${mix(a.x,b.x,p)}px,${mix(a.y,b.y,p)}px) rotate(${mix(a.rotation,b.rotation,p)}deg) scale(${mix(a.scaleX,b.scaleX,p)},${mix(a.scaleY,b.scaleY,p)})`;n.joint.style.opacity=String(mix(a.opacity,b.opacity,p));const src=n.def.expressions?.[expr]||n.def.src,full=c.base+src;if(n.img.dataset.src!==full){n.img.src=full;n.img.dataset.src=full;}}c.resolved={view,expression:expr,action,progress};return c;}
  M.__NS__={manifest:CHARACTER,puppet:PUPPET,capacidades:capabilities,
    insertar(padre,prefijo="__SLUG__",opts={}){padre=M.$(padre);const wrap=M.html("div",{id:prefijo+"-wrap",class:"__SLUG__-wrap"},padre),stage=M.html("div",{id:prefijo+"-stage",class:"__SLUG__-stage"},wrap),first=PUPPET.views[DEFAULT_VIEW],bounds=first.contentBounds||[0,0,first.canvas[0],first.canvas[1]],nativeW=Math.max(1,bounds[2]-bounds[0]),nativeH=Math.max(1,bounds[3]-bounds[1]),ancho=num(opts.ancho,nativeW),baseScale=ancho/nativeW,alto=nativeH*baseScale,base=opts.base||"__ASSET_PREFIX__/__SLUG__/";wrap.style.cssText=`position:absolute;width:${ancho}px;height:${alto}px;transform-origin:${(first.anchor[0]-bounds[0])*baseScale}px ${(first.anchor[1]-bounds[1])*baseScale}px;${opts.estilo||""}`;stage.style.cssText=`position:absolute;left:${-bounds[0]*baseScale}px;top:${-bounds[1]*baseScale}px;width:${first.canvas[0]}px;height:${first.canvas[1]}px;transform:scale(${baseScale});transform-origin:0 0;`;const rigs={};for(const [name,def] of Object.entries(PUPPET.views))rigs[name]=buildRig(stage,name,def,base);const c={wrap,stage,rigs,base,ancho,baseScale,contentBounds:bounds,resolved:null};apply(c,{action:opts.action||"idle",view:opts.view||DEFAULT_VIEW,expression:opts.expression||DEFAULT_EXPRESSION},1);return c;},
    posar(c,state={}){return apply(c,state,1);},
    animar(tl,c,at,dur,state={}){M.porCuadro(tl,at,dur,p=>apply(c,state,p),state.ease||"none");return c;},
    accion(tl,c,action,at,dur,opts={}){return this.animar(tl,c,at,dur,{...opts,action});},
    ciclo(tl,c,at,dur,poses=["walk-a","walk-b"],opts={}){const seq=[...poses].filter(Boolean);if(seq.length<2)throw new Error("ciclo() needs at least two pose names");const reps=Math.max(1,num(opts.repeticiones,1));M.porCuadro(tl,at,dur,p=>{const phase=p*seq.length*reps,i=Math.floor(phase)%seq.length,q=phase-Math.floor(phase),from=seq[i],to=seq[(i+1)%seq.length];apply(c,{...opts,fromAction:from,action:to},q);},opts.ease||"none");return c;},
    entrar(tl,c,at=0,desde="abajo",dur=.65){const d={abajo:{y:300},izquierda:{x:-400},derecha:{x:400}}[desde]||{y:300};tl.fromTo(c.wrap,{...d,opacity:0},{x:0,y:0,opacity:1,duration:dur,ease:"back.out(1.4)"},at);return c;},
    saltar(tl,c,at=0,dur=.8,altura=70){if(!M.anim)return tl.fromTo(c.wrap,{y:0},{y:-altura,duration:dur/2,yoyo:true,repeat:1,ease:"power2.out"},at),c;M.porCuadro(tl,at,dur,p=>{const t=p*dur,j=M.anim.jump(t,dur*.18,dur*.78,altura);gsap.set(c.wrap,{y:j.y,scaleX:1+j.squash*.45,scaleY:1-j.squash,transformOrigin:"50% 100%"});},"none");return c;},
    reaccionar(tl,c,at=0,dur=.55,intensidad=1){if(!M.anim)return c;M.porCuadro(tl,at,dur,p=>{const q=M.anim.take(p*dur,.08,intensidad);gsap.set(c.wrap,{y:q.y*18,scaleX:1+q.squash*.35,scaleY:1-q.squash,transformOrigin:"50% 100%"});},"none");return c;}
  };
})();
'''

DEMO = '''<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"></head><body>\n<template>\n<style>#__DEMO__{position:absolute;inset:0;background:#fff}#__DEMO__ .hint{position:absolute;left:80px;top:70px;font:36px/1.2 system-ui;color:#111}</style>\n<div id="__DEMO__" data-composition-id="__DEMO__" data-width="1920" data-height="1080"><div class="hint">__NAME__ · generated character demo</div></div>\n<script>(()=>{const tl=gsap.timeline({paused:true});const c=__RUNTIME__.__NS__.insertar("#__DEMO__","__DEMO__-c",{ancho:640,estilo:"left:640px;top:260px;"});__RUNTIME__.__NS__.entrar(tl,c,.1,"abajo");__RUNTIME__.__NS__.animar(tl,c,.8,2.4,{action:"__ACTION__",view:"__VIEW__",expression:"__EXPR__"});window.__timelines["__DEMO__"]=tl;})();</script>\n</template></body></html>\n'''

SPRITE_README = '''# __NAME__ · HyperFrames character export

Generated by **Mafia AI Character Creator**.

## Runtime requirements

- `window.__RUNTIME__` from the selected target.
- GSAP.
- `__RUNTIME__.porCuadro` for seek-safe sprite playback.
- `__RUNTIME__.anim` is optional and only used by helper acting such as `saltar()` and `reaccionar()`.
- Keep `atlas.webp` and `atlas.json` in this character directory.

## API

```js
const c = __RUNTIME__.__NS__.insertar("#scene", "my-character", {
  ancho: 640,
  estilo: "left:800px;top:260px;"
});
__RUNTIME__.__NS__.animar(tl, c, 1, 2, { action: "__ACTION__", view: "__VIEW__", expression: "__EXPR__" });
```

`ancho` sets the rendered character cell width without changing the atlas or fighting wrapper squash/stretch.

## Target integration

This export targets `__TARGET__` and writes to `__CHARACTER_DIR__/`. Asset URLs use `__ASSET_PREFIX__/`.
Run the target's kit build command after export when its configuration defines one.

Use `--finalize` to run configured build and catalog commands and apply the target's version policy.
'''

PUPPET_README = '''# __NAME__ · HyperFrames raster-puppet export

Generated by **Mafia AI Character Creator**.

## Runtime requirements

- `window.__RUNTIME__` and GSAP.
- `__RUNTIME__.porCuadro` for seek-safe interpolation between named puppet poses.
- `__RUNTIME__.anim` is optional and powers `saltar()` / `reaccionar()`.
- Keep `puppet.json` and the `parts/` directory with this character.

## API

```js
const c = __RUNTIME__.__NS__.insertar("#scene", "my-character", { ancho: 640 });
__RUNTIME__.__NS__.animar(tl, c, 1, .45, { action: "__ACTION__", fromAction: "idle", view: "__VIEW__", expression: "__EXPR__" });
__RUNTIME__.__NS__.saltar(tl, c, 2, .8, 90);
```

Named puppet poses are targets; `animar()` interpolates joints from `fromAction` (default `idle`) to the requested pose. `ciclo()` interpolates repeatedly between two or more poses, for example `walk-a` and `walk-b`. Larger body motion should normally happen on the wrapper with GSAP/`__RUNTIME__.anim`.

`ancho` means the visible neutral character width in the default view. It is calculated from `contentBounds`, not from the authoring canvas, so a 1024×1024 rig does not make the character artificially small.

If `character.json` declares views/actions that the puppet does not actually implement, export fails instead of silently falling back. Use `--sync-manifest` only when you intentionally want the exporter to align the manifest to the real puppet capabilities.

## Target integration

This export targets `__TARGET__` and writes to `__CHARACTER_DIR__/`. Asset URLs use `__ASSET_PREFIX__/`.
Run the target's kit build command after export when its configuration defines one.

Use `--finalize` to run configured build and catalog commands and apply the target's version policy.
'''



def firsts(m):
    return ((m.get('actions') or ['idle'])[0], (m.get('requiredViews') or m.get('views') or ['front'])[0], (m.get('expressions') or ['neutral'])[0])


def copy_sprite(root: Path, out: Path, atlas: dict):
    source_img = root / 'assets' / atlas['image']
    dest_img = out / 'atlas.webp'
    with Image.open(source_img) as im:
        im.convert('RGBA').save(dest_img, 'WEBP', lossless=True, method=4)
    atlas2 = dict(atlas); atlas2['image'] = 'atlas.webp'; write_json(out / 'atlas.json', atlas2)
    return atlas2


def export_sprite(root, out, manifest, slug, ns, target):
    atlas = read_json(root/'assets/atlas.json')
    atlas2 = copy_sprite(root,out,atlas)
    m=dict(manifest);m['moduleSystem']='global';m['hyperframesNamespace']=ns;m['hyperframesTarget']=target['id']
    (out/f'{slug}.js').write_text(SPRITE_JS.replace('__CHARACTER__',js_json(m)).replace('__ATLAS__',js_json(atlas2)).replace('__NS__',ns).replace('__SLUG__',slug).replace('__RUNTIME__',target['runtime']).replace('__ASSET_PREFIX__',target['assetPrefix']),encoding='utf-8')
    action,view,expr=firsts(m)
    runtime=target['runtime']
    ficha={'nombre':slug,'tipo':'personaje','descripcion':m['description'],'licencia':'propia',
           'uso':f'const c = {runtime}.{ns}.insertar("#scene", "{slug}-1", {{ ancho: 640 }});\n{runtime}.{ns}.animar(tl, c, 0, 2, {{ action: "{action}", view: "{view}", expression: "{expr}" }});',
           'parametros':{'insertar(padre,prefijo,{ancho,estilo,src,action,view,expression})':'crea la instancia; ancho controla el tamaño visual sin reescalar el atlas',
                         'animar(tl,c,t,dur,state)':f'reproduce sprites seek-safe con {runtime}.porCuadro','accion(tl,c,action,t,dur,opts)':'atajo de acción','entrar(tl,c,t,desde,dur)':'entrada del wrapper',
                         'saltar/reaccionar':f'acting del wrapper; usa {runtime}.anim si está disponible'},
           'demo':{'archivo':'demo.html','id':f'demo-{slug}','duracion':4,'t':2,'formato':'16x9'}}
    write_json(out/'ficha.json',ficha)
    (out/'README.md').write_text(SPRITE_README.replace('__NAME__',m['displayName']).replace('__NS__',ns).replace('__ACTION__',action).replace('__VIEW__',view).replace('__EXPR__',expr).replace('__RUNTIME__',target['runtime']).replace('__TARGET__',target['id']).replace('__CHARACTER_DIR__',target['characterDir']).replace('__ASSET_PREFIX__',target['assetPrefix']),encoding='utf-8')
    return action,view,expr



def puppet_capabilities(puppet):
    views=list((puppet.get('views') or {}).keys())
    actions_by_view={v:set((rig.get('poses') or {}).keys()) for v,rig in (puppet.get('views') or {}).items()}
    expressions={puppet.get('defaultExpression','neutral')}
    for rig in (puppet.get('views') or {}).values():
        for part in rig.get('parts') or []: expressions.update((part.get('expressions') or {}).keys())
    return views,actions_by_view,sorted(expressions)

def sync_or_validate_puppet_manifest(root,manifest,puppet,sync=False):
    views,actions_by_view,expressions=puppet_capabilities(puppet)
    if not views: raise SystemExit('puppet has no views')
    m=dict(manifest); declared_views=list(m.get('views') or []); required=list(m.get('requiredViews') or declared_views or [puppet.get('defaultView') or views[0]])
    missing_views=[v for v in declared_views if v not in views]; missing_required=[v for v in required if v not in views]
    if sync:
        required=[v for v in required if v in views] or [puppet.get('defaultView') if puppet.get('defaultView') in views else views[0]]
        common=set(actions_by_view[required[0]]) if required else set()
        for v in required[1:]: common &= actions_by_view[v]
        ordered_actions=[a for a in (m.get('actions') or []) if a in common] + sorted(common-set(m.get('actions') or []))
        m['views']=views;m['requiredViews']=required;m['actions']=ordered_actions;m['expressions']=expressions
        write_json(root/'character.json',m)
        return m
    if missing_views: raise SystemExit(f'character.json declares puppet views not implemented: {missing_views}. Use --sync-manifest to align it to puppet.json.')
    if missing_required: raise SystemExit(f'character.json requiredViews missing from puppet: {missing_required}. Use --sync-manifest to align it to puppet.json.')
    for view in required:
        missing_actions=set(m.get('actions') or [])-actions_by_view.get(view,set())
        if missing_actions: raise SystemExit(f'view {view} missing declared puppet poses: {sorted(missing_actions)}')
    missing_expr=set(m.get('expressions') or [])-set(expressions)
    if missing_expr: raise SystemExit(f'puppet does not implement declared expressions: {sorted(missing_expr)}')
    return m

def ensure_puppet_content_bounds(puppet,asset_root):
    for view,rig in (puppet.get('views') or {}).items():
        parts=rig.get('parts') or []; by={p.get('id'):p for p in parts}; memo={}
        def joint_abs(pid):
            if pid in memo:return memo[pid]
            part=by[pid];x=float(part.get('x',0));y=float(part.get('y',0));parent=part.get('parent')
            if parent:
                if parent not in by: raise SystemExit(f'view {view}: missing parent {parent} for {pid}')
                px,py=joint_abs(parent);x+=px;y+=py
            memo[pid]=(x,y);return memo[pid]
        boxes=[]
        for part in parts:
            pid=part.get('id');
            if not pid: continue
            x,y=joint_abs(pid);px,py=(part.get('pivot') or [0,0]);refs=[part.get('src')]+list((part.get('expressions') or {}).values())
            dims=[]
            for rel in refs:
                if not rel: continue
                f=asset_root/rel
                if not f.is_file(): raise SystemExit(f'missing puppet asset: {f}')
                with Image.open(f) as im:dims.append(im.size)
            if not dims: continue
            maxw=max(w for w,h in dims);maxh=max(h for w,h in dims);boxes.append((x-px,y-py,x-px+maxw,y-py+maxh))
        if boxes:
            l=min(b[0] for b in boxes);t=min(b[1] for b in boxes);r=max(b[2] for b in boxes);b=max(b[3] for b in boxes)
            rig['contentBounds']=[round(l,2),round(t,2),round(r,2),round(b,2)];rig['contentSize']=[round(r-l,2),round(b-t,2)]
    return puppet

def export_puppet(root,out,manifest,slug,ns,target,sync_manifest=False):
    source_pp=root/'assets/puppet.json'; puppet=read_json(source_pp)
    m=sync_or_validate_puppet_manifest(root,manifest,puppet,sync=sync_manifest)
    puppet=ensure_puppet_content_bounds(puppet,source_pp.parent)
    parts_src=root/'assets/parts';parts_dst=out/'parts'
    if parts_dst.exists():shutil.rmtree(parts_dst)
    shutil.copytree(parts_src,parts_dst)
    # HyperFrames output keeps authoring paths relative to this character directory.
    pp=json.loads(json.dumps(puppet))
    for rig in (pp.get('views') or {}).values():
        for part in rig.get('parts') or []:
            src=part.get('src','')
            if not src.startswith('parts/'): part['src']='parts/'+Path(src).name
            for k,v in list((part.get('expressions') or {}).items()):
                if not v.startswith('parts/'): part['expressions'][k]='parts/'+Path(v).name
    write_json(out/'puppet.json',pp)
    m=dict(m);m['moduleSystem']='global';m['hyperframesNamespace']=ns;m['hyperframesTarget']=target['id'];m['renderMode']='raster-puppet'
    (out/f'{slug}.js').write_text(PUPPET_JS.replace('__CHARACTER__',js_json(m)).replace('__PUPPET__',js_json(pp)).replace('__NS__',ns).replace('__SLUG__',slug).replace('__RUNTIME__',target['runtime']).replace('__ASSET_PREFIX__',target['assetPrefix']),encoding='utf-8')
    action,view,expr=firsts(m)
    runtime=target['runtime']
    ficha={'nombre':slug,'tipo':'personaje','descripcion':m['description'],'licencia':'propia',
           'uso':f'const c = {runtime}.{ns}.insertar("#scene", "{slug}-1", {{ ancho: 640 }});\n{runtime}.{ns}.animar(tl, c, 0, .45, {{ action: "{action}", fromAction: "idle", view: "{view}", expression: "{expr}" }});',
           'parametros':{'insertar(padre,prefijo,{ancho,estilo,base,action,view,expression})':'crea el puppet; ancho es el ancho visual del personaje neutral en la vista por defecto, no el lienzo de autoría',
                         'posar(c,state)':'aplica inmediatamente una pose/vista/expresión','animar(tl,c,t,dur,state)':'interpola articulaciones seek-safe desde fromAction a action','accion(tl,c,action,t,dur,opts)':'atajo de pose animada',
                         'ciclo(tl,c,t,dur,poses,opts)':'interpola cíclicamente entre dos o más poses (p. ej. walk-a/walk-b)','entrar(tl,c,t,desde,dur)':'entrada del wrapper',
                         'saltar/reaccionar':f'acting del wrapper con {runtime}.anim si está disponible'},
           'demo':{'archivo':'demo.html','id':f'demo-{slug}','duracion':4,'t':2,'formato':'16x9'}}
    write_json(out/'ficha.json',ficha)
    (out/'README.md').write_text(PUPPET_README.replace('__NAME__',m['displayName']).replace('__NS__',ns).replace('__ACTION__',action).replace('__VIEW__',view).replace('__EXPR__',expr).replace('__RUNTIME__',target['runtime']).replace('__TARGET__',target['id']).replace('__CHARACTER_DIR__',target['characterDir']).replace('__ASSET_PREFIX__',target['assetPrefix']),encoding='utf-8')
    return action,view,expr


def safe_target_path(value, label):
    if not isinstance(value, str) or not value or Path(value).is_absolute() or "\\" in value:
        raise SystemExit(f"invalid target {label}: {value!r}")
    parts = Path(value).parts
    if any(part in {"", ".", ".."} for part in parts):
        raise SystemExit(f"unsafe target {label}: {value!r}")
    return Path(*parts)


def target_command(value, label):
    import shlex
    if value is None:
        return None
    command = shlex.split(value) if isinstance(value, str) else value
    if not isinstance(command, list) or not command or any(not isinstance(part, str) or not part for part in command):
        raise SystemExit(f"invalid target {label}; use a command string or argv array")
    return command


def load_target(target_id, project_root, config_path=None):
    skill_root = Path(__file__).resolve().parents[1]
    if config_path:
        candidate = Path(config_path).expanduser()
        if not candidate.is_absolute(): candidate = project_root / candidate
    else:
        private_target = project_root / "tools" / "skill-targets" / f"{target_id}.json"
        bundled_target = skill_root / "adapters" / target_id / "target.json"
        candidate = private_target if private_target.is_file() else bundled_target
    if not candidate.is_file():
        raise SystemExit(f"target config not found for {target_id}: {candidate}")
    target = read_json(candidate)
    if target.get("schemaVersion") != 1 or target.get("id") != target_id:
        raise SystemExit(f"invalid target config identity in {candidate}")
    target["characterDir"] = safe_target_path(target.get("characterDir"), "characterDir").as_posix()
    target["assetPrefix"] = safe_target_path(target.get("assetPrefix"), "assetPrefix").as_posix()
    runtime = target.get("runtime")
    if not isinstance(runtime, str) or not re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", runtime):
        raise SystemExit(f"invalid target runtime global: {runtime!r}")
    target["runtime"] = runtime
    for key in ("versionFile",):
        if target.get(key): target[key] = safe_target_path(target[key], key).as_posix()
    for key in ("buildCommand", "catalogCommand"):
        if target.get(key): target[key] = target_command(target[key], key)
    if target.get("versionBump", "minor") != "minor":
        raise SystemExit("only the 'minor' target version bump policy is supported")
    return target


def finalize_target(project_root: Path, target: dict):
    version_path = project_root / target["versionFile"] if target.get("versionFile") else None
    old_content = version_path.read_text(encoding="utf-8") if version_path else None
    old_version = old_content.strip() if old_content is not None else None
    new_version = None
    if version_path:
        match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", old_version or "")
        if not match: raise SystemExit(f"unsupported target version: {old_version}")
        new_version = f"{match.group(1)}.{int(match.group(2)) + 1}.0"
        version_path.write_text(new_version + "\n", encoding="utf-8")
    commands = [cmd for cmd in (target.get("buildCommand"), target.get("catalogCommand")) if cmd]
    try:
        for command in commands:
            subprocess.run(command, cwd=project_root, check=True)
    except Exception:
        if version_path and old_content is not None:
            version_path.write_text(old_content, encoding="utf-8")
        raise
    return {"oldVersion": old_version, "newVersion": new_version, "commands": commands}


def main():
    p=argparse.ArgumentParser(description=__doc__)
    sub=p.add_subparsers(dest='command',required=True)
    character=sub.add_parser('character',help='export a character package to a configured target')
    character.add_argument('package')
    character.add_argument('--target',required=True,help='target id, such as code-to-video-studio')
    character.add_argument('--target-config',default='',help='explicit target JSON; otherwise project-local and bundled targets are checked')
    character.add_argument('--project-root',default='.',help='target repository root (default: current directory)')
    character.add_argument('--slug',default='')
    character.add_argument('--namespace',default='')
    character.add_argument('--sync-manifest',action='store_true',help='For raster-puppet, align character.json views/actions/expressions to the actual puppet capabilities before export')
    character.add_argument('--finalize',action='store_true',help='Apply target version policy and run configured build/catalog commands')
    character.add_argument('--force',action='store_true',help='replace an existing exported character directory')
    a=p.parse_args()

    project_root=Path(a.project_root).expanduser().resolve()
    target=load_target(a.target,project_root,a.target_config or None)
    root=Path(a.package).expanduser().resolve();m=read_json(root/'character.json')
    slug=a.slug or slugify(m['id']);ns=a.namespace or namespace_for(slug)
    output_root=project_root/target['characterDir'];out=output_root/slug
    if out.exists() and not a.force: raise SystemExit(f'output already exists: {out}; pass --force to replace it')
    output_root.mkdir(parents=True,exist_ok=True)
    stage=Path(tempfile.mkdtemp(prefix=f'.{slug}.tmp-',dir=output_root))
    backup=output_root/f'.{slug}.backup-{Path(stage).name.rsplit("-",1)[-1]}'
    try:
        mode=m.get('renderMode')
        if mode in {'generated-art','raster-sprites'}: action,view,expr=export_sprite(root,stage,m,slug,ns,target)
        elif mode=='raster-puppet': action,view,expr=export_puppet(root,stage,m,slug,ns,target,a.sync_manifest)
        else: raise SystemExit('HyperFrames exporter supports generated-art/raster-sprites and raster-puppet packages')
        demo_id=f'demo-{slug}'
        (stage/'demo.html').write_text(DEMO.replace('__DEMO__',demo_id).replace('__NAME__',m['displayName']).replace('__NS__',ns).replace('__RUNTIME__',target['runtime']).replace('__ACTION__',action).replace('__VIEW__',view).replace('__EXPR__',expr),encoding='utf-8')
        if out.exists(): out.rename(backup)
        try:
            stage.rename(out)
        except BaseException:
            if backup.exists() and not out.exists(): backup.rename(out)
            raise
        if backup.exists(): shutil.rmtree(backup)
    except BaseException:
        if stage.exists(): shutil.rmtree(stage,ignore_errors=True)
        if backup.exists() and not out.exists(): backup.rename(out)
        raise
    finalized=finalize_target(project_root,target) if a.finalize else None
    next_steps=[] if finalized else (["Run target build command: " + " ".join(target['buildCommand'])] if target.get('buildCommand') else [])
    print(json.dumps({'ok':True,'output':str(out),'mode':mode,'target':target['id'],'namespace':f"{target['runtime']}.{ns}",'files':[p.name for p in sorted(out.iterdir())],'finalized':finalized,'nextSteps':next_steps},indent=2))

if __name__=='__main__':main()
